<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            ['code' => 'USD', 'symbol' => '$',    'name' => 'US Dollar',             'exchange_rate' => 1],
            ['code' => 'EUR', 'symbol' => '€',    'name' => 'Euro',                  'exchange_rate' => 0.92],
            ['code' => 'GBP', 'symbol' => '£',    'name' => 'British Pound',         'exchange_rate' => 0.79],
            ['code' => 'JPY', 'symbol' => '¥',    'name' => 'Japanese Yen',          'exchange_rate' => 155],
            ['code' => 'CNY', 'symbol' => '¥',    'name' => 'Chinese Yuan',          'exchange_rate' => 7.24],
            ['code' => 'INR', 'symbol' => '₹',    'name' => 'Indian Rupee',          'exchange_rate' => 83],
            ['code' => 'CAD', 'symbol' => 'CA$',  'name' => 'Canadian Dollar',       'exchange_rate' => 1.36],
            ['code' => 'AUD', 'symbol' => 'A$',   'name' => 'Australian Dollar',     'exchange_rate' => 1.54],
            ['code' => 'CHF', 'symbol' => 'CHF',  'name' => 'Swiss Franc',           'exchange_rate' => 0.90],
            ['code' => 'HKD', 'symbol' => 'HK$',  'name' => 'Hong Kong Dollar',      'exchange_rate' => 7.82],
            ['code' => 'SGD', 'symbol' => 'S$',   'name' => 'Singapore Dollar',      'exchange_rate' => 1.35],
            ['code' => 'SEK', 'symbol' => 'kr',   'name' => 'Swedish Krona',         'exchange_rate' => 10.5],
            ['code' => 'NOK', 'symbol' => 'kr',   'name' => 'Norwegian Krone',       'exchange_rate' => 10.6],
            ['code' => 'DKK', 'symbol' => 'kr',   'name' => 'Danish Krone',          'exchange_rate' => 6.88],
            ['code' => 'NZD', 'symbol' => 'NZ$',  'name' => 'New Zealand Dollar',    'exchange_rate' => 1.63],
            ['code' => 'KRW', 'symbol' => '₩',    'name' => 'South Korean Won',      'exchange_rate' => 1340],
            ['code' => 'MXN', 'symbol' => '$',    'name' => 'Mexican Peso',          'exchange_rate' => 17.1],
            ['code' => 'BRL', 'symbol' => 'R$',   'name' => 'Brazilian Real',        'exchange_rate' => 5.05],
            ['code' => 'ZAR', 'symbol' => 'R',    'name' => 'South African Rand',    'exchange_rate' => 18.5],
            ['code' => 'TRY', 'symbol' => '₺',    'name' => 'Turkish Lira',          'exchange_rate' => 32.5],
            ['code' => 'RUB', 'symbol' => '₽',    'name' => 'Russian Ruble',         'exchange_rate' => 91],
            ['code' => 'AED', 'symbol' => 'AED',  'name' => 'UAE Dirham',            'exchange_rate' => 3.67],
            ['code' => 'SAR', 'symbol' => 'SAR',  'name' => 'Saudi Riyal',           'exchange_rate' => 3.75],
            ['code' => 'QAR', 'symbol' => 'QR',   'name' => 'Qatari Riyal',          'exchange_rate' => 3.64],
            ['code' => 'KWD', 'symbol' => 'KD',   'name' => 'Kuwaiti Dinar',         'exchange_rate' => 0.31],
            ['code' => 'BHD', 'symbol' => 'BD',   'name' => 'Bahraini Dinar',        'exchange_rate' => 0.38],
            ['code' => 'OMR', 'symbol' => 'OMR',  'name' => 'Omani Rial',            'exchange_rate' => 0.38],
            ['code' => 'JOD', 'symbol' => 'JD',   'name' => 'Jordanian Dinar',       'exchange_rate' => 0.71],
            ['code' => 'EGP', 'symbol' => 'E£',   'name' => 'Egyptian Pound',        'exchange_rate' => 47.5],
            ['code' => 'NGN', 'symbol' => '₦',    'name' => 'Nigerian Naira',        'exchange_rate' => 1580],
            ['code' => 'KES', 'symbol' => 'KSh',  'name' => 'Kenyan Shilling',       'exchange_rate' => 131],
            ['code' => 'GHS', 'symbol' => 'GH₵',  'name' => 'Ghanaian Cedi',         'exchange_rate' => 14.5],
            ['code' => 'TZS', 'symbol' => 'TSh',  'name' => 'Tanzanian Shilling',    'exchange_rate' => 2600],
            ['code' => 'UGX', 'symbol' => 'USh',  'name' => 'Ugandan Shilling',      'exchange_rate' => 3800],
            ['code' => 'ETB', 'symbol' => 'Br',   'name' => 'Ethiopian Birr',        'exchange_rate' => 56],
            ['code' => 'MAD', 'symbol' => 'MAD',  'name' => 'Moroccan Dirham',       'exchange_rate' => 10.0],
            ['code' => 'DZD', 'symbol' => 'DA',   'name' => 'Algerian Dinar',        'exchange_rate' => 134],
            ['code' => 'TND', 'symbol' => 'DT',   'name' => 'Tunisian Dinar',        'exchange_rate' => 3.12],
            ['code' => 'XOF', 'symbol' => 'CFA',  'name' => 'West African CFA',      'exchange_rate' => 602],
            ['code' => 'PKR', 'symbol' => '₨',    'name' => 'Pakistani Rupee',       'exchange_rate' => 278],
            ['code' => 'BDT', 'symbol' => '৳',    'name' => 'Bangladeshi Taka',      'exchange_rate' => 110],
            ['code' => 'LKR', 'symbol' => 'Rs',   'name' => 'Sri Lankan Rupee',      'exchange_rate' => 305],
            ['code' => 'NPR', 'symbol' => 'Rs',   'name' => 'Nepalese Rupee',        'exchange_rate' => 133],
            ['code' => 'MMK', 'symbol' => 'MMK ', 'name' => 'Myanmar Kyat',          'exchange_rate' => 2100],
            ['code' => 'THB', 'symbol' => '฿',    'name' => 'Thai Baht',             'exchange_rate' => 36],
            ['code' => 'MYR', 'symbol' => 'RM',   'name' => 'Malaysian Ringgit',     'exchange_rate' => 4.70],
            ['code' => 'IDR', 'symbol' => 'Rp',   'name' => 'Indonesian Rupiah',     'exchange_rate' => 15900],
            ['code' => 'PHP', 'symbol' => '₱',    'name' => 'Philippine Peso',       'exchange_rate' => 57],
            ['code' => 'VND', 'symbol' => '₫',    'name' => 'Vietnamese Dong',       'exchange_rate' => 25400],
            ['code' => 'KHR', 'symbol' => '៛',    'name' => 'Cambodian Riel',        'exchange_rate' => 4100],
            ['code' => 'LAK', 'symbol' => '₭',    'name' => 'Lao Kip',               'exchange_rate' => 21500],
            ['code' => 'TWD', 'symbol' => 'NT$',  'name' => 'Taiwan Dollar',         'exchange_rate' => 32],
            ['code' => 'MNT', 'symbol' => '₮',    'name' => 'Mongolian Tugrik',      'exchange_rate' => 3400],
            ['code' => 'KZT', 'symbol' => '₸',    'name' => 'Kazakhstani Tenge',     'exchange_rate' => 450],
            ['code' => 'UZS', 'symbol' => 'soʻm', 'name' => 'Uzbekistani Som',       'exchange_rate' => 12700],
            ['code' => 'GEL', 'symbol' => '₾',    'name' => 'Georgian Lari',         'exchange_rate' => 2.68],
            ['code' => 'AMD', 'symbol' => '֏',    'name' => 'Armenian Dram',         'exchange_rate' => 387],
            ['code' => 'AZN', 'symbol' => '₼',    'name' => 'Azerbaijani Manat',     'exchange_rate' => 1.70],
            ['code' => 'UAH', 'symbol' => '₴',    'name' => 'Ukrainian Hryvnia',     'exchange_rate' => 39],
            ['code' => 'PLN', 'symbol' => 'zł',   'name' => 'Polish Zloty',          'exchange_rate' => 4.00],
            ['code' => 'CZK', 'symbol' => 'Kč',   'name' => 'Czech Koruna',          'exchange_rate' => 23],
            ['code' => 'HUF', 'symbol' => 'Ft',   'name' => 'Hungarian Forint',      'exchange_rate' => 360],
            ['code' => 'RON', 'symbol' => 'lei',  'name' => 'Romanian Leu',          'exchange_rate' => 4.58],
            ['code' => 'BGN', 'symbol' => 'лв',   'name' => 'Bulgarian Lev',         'exchange_rate' => 1.80],
            ['code' => 'HRK', 'symbol' => 'kn',   'name' => 'Croatian Kuna',         'exchange_rate' => 7.08],
            ['code' => 'RSD', 'symbol' => 'din',  'name' => 'Serbian Dinar',         'exchange_rate' => 108],
            ['code' => 'ISK', 'symbol' => 'kr',   'name' => 'Icelandic Krona',       'exchange_rate' => 138],
            ['code' => 'CLP', 'symbol' => 'CL$',  'name' => 'Chilean Peso',          'exchange_rate' => 920],
            ['code' => 'COP', 'symbol' => 'CO$',  'name' => 'Colombian Peso',        'exchange_rate' => 3900],
            ['code' => 'PEN', 'symbol' => 'S/',   'name' => 'Peruvian Sol',          'exchange_rate' => 3.76],
            ['code' => 'ARS', 'symbol' => 'AR$',  'name' => 'Argentine Peso',        'exchange_rate' => 890],
            ['code' => 'BOB', 'symbol' => 'Bs',   'name' => 'Bolivian Boliviano',    'exchange_rate' => 6.91],
            ['code' => 'PYG', 'symbol' => '₲',    'name' => 'Paraguayan Guarani',    'exchange_rate' => 7350],
            ['code' => 'UYU', 'symbol' => '$U',   'name' => 'Uruguayan Peso',        'exchange_rate' => 38.5],
            ['code' => 'VES', 'symbol' => 'Bs.S', 'name' => 'Venezuelan Bolívar',    'exchange_rate' => 36.5],
            ['code' => 'GTQ', 'symbol' => 'Q',    'name' => 'Guatemalan Quetzal',    'exchange_rate' => 7.80],
            ['code' => 'HNL', 'symbol' => 'L',    'name' => 'Honduran Lempira',      'exchange_rate' => 24.7],
            ['code' => 'CRC', 'symbol' => '₡',    'name' => 'Costa Rican Colón',     'exchange_rate' => 519],
            ['code' => 'DOP', 'symbol' => 'RD$',  'name' => 'Dominican Peso',        'exchange_rate' => 58.5],
            ['code' => 'JMD', 'symbol' => 'J$',   'name' => 'Jamaican Dollar',       'exchange_rate' => 156],
            ['code' => 'TTD', 'symbol' => 'TT$',  'name' => 'Trinidad Dollar',       'exchange_rate' => 6.79],
            ['code' => 'BBD', 'symbol' => 'Bds$', 'name' => 'Barbadian Dollar',      'exchange_rate' => 2.00],
            ['code' => 'ILS', 'symbol' => '₪',    'name' => 'Israeli New Shekel',    'exchange_rate' => 3.72],
            ['code' => 'IRR', 'symbol' => '﷼',    'name' => 'Iranian Rial',          'exchange_rate' => 42000],
            ['code' => 'IQD', 'symbol' => 'IQD',  'name' => 'Iraqi Dinar',           'exchange_rate' => 1310],
            ['code' => 'LBP', 'symbol' => 'L£',   'name' => 'Lebanese Pound',        'exchange_rate' => 89500],
            ['code' => 'SYP', 'symbol' => 'S£',   'name' => 'Syrian Pound',          'exchange_rate' => 13000],
            ['code' => 'AFN', 'symbol' => '؋',    'name' => 'Afghan Afghani',        'exchange_rate' => 70.5],
            ['code' => 'MOP', 'symbol' => 'P',    'name' => 'Macanese Pataca',       'exchange_rate' => 8.06],
            ['code' => 'FJD', 'symbol' => 'FJ$',  'name' => 'Fijian Dollar',         'exchange_rate' => 2.25],
            ['code' => 'PGK', 'symbol' => 'K',    'name' => 'Papua New Guinea Kina', 'exchange_rate' => 3.73],
            ['code' => 'XPF', 'symbol' => 'Fr',   'name' => 'CFP Franc',             'exchange_rate' => 110],
            ['code' => 'MZN', 'symbol' => 'MT',   'name' => 'Mozambican Metical',    'exchange_rate' => 63.7],
            ['code' => 'ZMW', 'symbol' => 'ZK',   'name' => 'Zambian Kwacha',        'exchange_rate' => 26.4],
            ['code' => 'BWP', 'symbol' => 'P',    'name' => 'Botswana Pula',         'exchange_rate' => 13.6],
            ['code' => 'NAD', 'symbol' => 'N$',   'name' => 'Namibian Dollar',       'exchange_rate' => 18.5],
            ['code' => 'MUR', 'symbol' => '₨',    'name' => 'Mauritian Rupee',       'exchange_rate' => 45.5],
        ];

        foreach ($currencies as $curr) {
            Currency::firstOrCreate(['code' => $curr['code']], $curr);
        }
    }
}
